Send the data received to on_ipc_error event.
Ext-Creators/discord-ext-ipc pull request #25
Opened 2021-03-07 11:18 UTC by MeFaltaUnVerano21

### Description
Send the data received to on_ipc_error event.

- [x] This PR has been tested.

2021-03-07 11:45 UTC, Gobot1234 commented on discord/ext/ipc/server.py
> +                        self.bot.dispatch("ipc_error", request.get("data", None), endpoint, error)
dict.get by default returns None so the second argument is pointless

2021-03-07 12:55 UTC, MeFaltaUnVerano21 reviewed
Sry, fixed

2021-03-07 12:57 UTC, Gobot1234 commented
This is also a breaking change

2021-03-08 16:16 UTC, ShineyDev requested changes
Hey, thanks for the PR! As [mentioned above](https://github.com/Ext-Creators/discord-ext-ipc/pull/25#issuecomment-792274902) this isn't going to be merged as a breaking change, but that isn't to say that you cannot remedy it.

I suggest you discuss the design with @lgaan when he's around, but I have a few questions myself:
- What made you want to pass data through to the handler?
- Why should the data come before the endpoint in the handler call? Generally speaking, getting more specific with data as you go is correct.
- Why is data alone so important? I think passing the `request` object itself would be more useful.

2021-03-09 11:41 UTC, lgaan commented
I'll wait for the above questions to be answered. But for now my stance is that this is not needed.

2021-03-20 15:56 UTC, lgaan commented
I feel like a better design, and non breaking fix, for this would be to attach a `request` arg to the error parsed to the event.

2021-03-24 09:26 UTC, lgaan commented
Opening a pull request to implement this with the design above later. With that I will close this issue now.

2021-03-24 09:26 UTC, closed without merging